Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from ipyautoui.demo_schemas import CoreIpywidgets

user_file_renderers = AutoUi.create_autodisplay_map(
    ext=".aui.json", schema=CoreIpywidgets
)
tests_constants.PATH_TEST_AUI.write_text(
    CoreIpywidgets(int_text_req=3, int_text_nullable=None).model_dump_json(indent=4)
)

test_ui = AutoDisplay.from_paths(
    paths=[tests_constants.PATH_TEST_AUI],
    renderers=user_file_renderers,
    display_showhide=False,
)

display(test_ui)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[3], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mipyautoui[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdemo_schemas[39;00m [38;5;28;01mimport[39;00m CoreIpywidgets
[0;32m----> 3[0m user_file_renderers [38;5;241m=[39m AutoUi[38;5;241m.[39mcreate_autodisplay_map(
[1;32m      4[0m     ext[38;5;241m=[39m[38;5;124m"[39m[38;5;124m.aui.json[39m[38;5;124m"[39m, schema[38;5;241m=[39mCoreIpywidgets
[1;32m      5[0m )
[1;32m      6[0m tests_constants[38;5;241m.[39mPATH_TEST_AUI[38;5;241m.[39mwrite_text(
[1;32m      7[0m     CoreIpywidgets(int_text_req[38;5;241m=[39m[38;5;241m3[39m, int_text_nullable[38;5;241m=[39m[38;5;28;01mNone[39;00m)[38;5;241m.[39mmodel_dump_json(indent[38;5;241m=[39m[38;5;241m4[39m)
[1;32m      8[0m )
[1;32m     10[0m test_ui [38;5;241m=[39m AutoDisplay[38;5;241m.[39mfrom_paths(
[1;32m     11[0m     paths[38;5;241m=[39m[tests_constants[38;5;241m.[39mPATH_TEST_AUI],
[1;32m     12[0m     renderers[38;5;241m=[39muser_file_renderers,
[1;32m     13[0m     display_showhide[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m     14[0m )

[0;31mAttributeError[0m: 'function' object has no attribute 'create_autodisplay_map'

